---
env:
  es6: true
  node: true
  jest: true
extends:
  - eslint-config-airbnb
  - prettier
globals:
  Atomics: readable
  SharedArrayBuffer: readable
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  import/no-extraneous-dependencies:
    - 2
    - devDependencies: true
